//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeworx.Identity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeworx.Identity.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Invitation.
        /// </summary>
        internal static string AcceptInvitationPageTitle {
            get {
                return ResourceManager.GetString("AcceptInvitationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect..
        /// </summary>
        internal static string DefaultAuthenticationError {
            get {
                return ResourceManager.GetString("DefaultAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external account is already linked to a different user..
        /// </summary>
        internal static string ExternalAccountAlreadyLinkedError {
            get {
                return ResourceManager.GetString("ExternalAccountAlreadyLinkedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account is not yet linked..
        /// </summary>
        internal static string ExternalAccountNotLinkedError {
            get {
                return ResourceManager.GetString("ExternalAccountNotLinkedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an account exists that maches the given credentials, password reset instructions will be sent to you..
        /// </summary>
        internal static string ForgotPasswordCompletedMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPasswordPageTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected login error!.
        /// </summary>
        internal static string GenericLoginError {
            get {
                return ResourceManager.GetString("GenericLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This normally indicates that your browser does not support Windows authentication, wronge credentials were provided or Windows authentication support is disabled..
        /// </summary>
        internal static string Http401Description {
            get {
                return ResourceManager.GetString("Http401Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You could not be authenticated.
        /// </summary>
        internal static string Http401Header {
            get {
                return ResourceManager.GetString("Http401Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401 Unauthenticated.
        /// </summary>
        internal static string Http401PageTitle {
            get {
                return ResourceManager.GetString("Http401PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invitation code is expired!.
        /// </summary>
        internal static string InvitationCodeExpiredError {
            get {
                return ResourceManager.GetString("InvitationCodeExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invitation code is invalid!.
        /// </summary>
        internal static string InvitationCodeInvalidError {
            get {
                return ResourceManager.GetString("InvitationCodeInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invitation code is no longer valid!.
        /// </summary>
        internal static string InvitationCodeRedeemedError {
            get {
                return ResourceManager.GetString("InvitationCodeRedeemedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation feature is not supported!.
        /// </summary>
        internal static string InvitationNotSupportedError {
            get {
                return ResourceManager.GetString("InvitationNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript is disabled. We strongly recommend to enable it. Click the button below to continue..
        /// </summary>
        internal static string JavascriptErrorMessage {
            get {
                return ResourceManager.GetString("JavascriptErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is locked because a wrong password was entered too often..
        /// </summary>
        internal static string MaxFailedLoginAttemptsReached {
            get {
                return ResourceManager.GetString("MaxFailedLoginAttemptsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIDC Form_Post Response.
        /// </summary>
        internal static string OidcFormPostResponsePageTitle {
            get {
                return ResourceManager.GetString("OidcFormPostResponsePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or connect with.
        /// </summary>
        internal static string OrConnectWith {
            get {
                return ResourceManager.GetString("OrConnectWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or login with.
        /// </summary>
        internal static string OrLoginWith {
            get {
                return ResourceManager.GetString("OrLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot be equal to the login!.
        /// </summary>
        internal static string PasswordChangeEqualToLoginError {
            get {
                return ResourceManager.GetString("PasswordChangeEqualToLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        internal static string PasswordChangeNotMatchingError {
            get {
                return ResourceManager.GetString("PasswordChangeNotMatchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot be equal to the current password!.
        /// </summary>
        internal static string PasswordChangeSamePasswordError {
            get {
                return ResourceManager.GetString("PasswordChangeSamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        internal static string PasswordChangeWrongPasswordError {
            get {
                return ResourceManager.GetString("PasswordChangeWrongPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to login.
        /// </summary>
        internal static string ReturnToLogin {
            get {
                return ResourceManager.GetString("ReturnToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tenant.
        /// </summary>
        internal static string SelectTenantPageTitle {
            get {
                return ResourceManager.GetString("SelectTenantPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        internal static string SetAsDefault {
            get {
                return ResourceManager.GetString("SetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid provider!.
        /// </summary>
        internal static string UnknownLoginProviderError {
            get {
                return ResourceManager.GetString("UnknownLoginProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User provided for client {0} could not be found..
        /// </summary>
        internal static string UserForClientP0NotFoundError {
            get {
                return ResourceManager.GetString("UserForClientP0NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
