namespace Codeworx.Identity.Resources
{
    public enum StringResource
    {
        Username,
        Password,
        RememberMe,
        ForgotPassword,
        Login,
        ChangePassword,
        ConfirmPassword,
        Save,
        JavascriptErrorMessage,
        Continue,
        OidcFormPostResponsePageTitle,
        Http401PageTitle,
        Http401Header,
        Http401Description,
        ReturnToLogin,
        ForgotPasswordPageTitle,
        ResetPassword,
        ForgotPasswordCompletedMessage,
        AcceptInvitationPageTitle,
        LoginPageTitle,
        ChangePasswordPageTitle,
        CurrentPassword,
        NewPassword,
        ProfilePageTitle,
        SelectTenantPageTitle,
        Select,
        SetAsDefault,
    }
}